CarsWebsite./ShowRoom/brands_app/urls.py
from django.urls import path
from .import views

app_name ="brands_app"

urlpatterns = [
    path('all/',views.all_brands_view, name='all_brands_view'),
    path('details/<int:brand_id>/',views.brand_detail_view, name='brand_detail_view'),
    path('new/',views.new_brand_view, name='new_brand_view'),
    path('update/<int:brand_id>/',views.update_brand_view, name='update_brand_view'),
    path('delete/<int:brand_id>/',views.brand_delete_view, name='brand_delete_view'),
]

CarsWebsite./ShowRoom/brands_app/models.py
from django.db import models
from django.urls import reverse

class Brand(models.Model):
    class BrandType(models.TextChoices):
        BMW = 'BMW', 'BMW'
        MAZDA = 'MAZDA', 'Mazda'
        TOYOTA = 'TOYOTA', 'Toyota'
        MERCEDES = 'MERCEDES', 'Mercedes'
        JEEP = 'JEEP', 'Jeep'
        FORD = 'FORD', 'Ford'
        DODGE = 'DODGE', 'Dodge'

    name = models.CharField(max_length=100)
    logo = models.ImageField(upload_to='brands/')
    about = models.TextField(blank=True)
    founded_at = models.DateField(null=True, blank=True)
    brand_type = models.CharField(max_length=20, choices=BrandType.choices, default=BrandType.BMW)


    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('brand_detail', args=[self.id])

    @property
    def car_count(self):
        return self.cars.count()  # Count of related cars

CarsWebsite./ShowRoom/brands_app/views.py
from django.shortcuts import render,redirect , get_object_or_404
from .models import Brand
from django.http import HttpRequest , HttpResponse
from .form import BrandForm
from django.contrib import messages


def all_brands_view(request:HttpRequest):
    brands = Brand.objects.all()  
    return render(request, 'brands_app/all_brands.html', {'brands': brands})
  
 

def brand_detail_view(request:HttpRequest,brand_id):
    brand = get_object_or_404(Brand, id=brand_id) 
    return render(request, 'brands_app/brand_detail.html', {'brand': brand})
 


def new_brand_view(request: HttpRequest):
    if request.method == 'POST':
        form = BrandForm(request.POST, request.FILES)
        if form.is_valid():
            form.save() 
            messages.success(request, "Brand created successfully!")
        return redirect('brands_app:all_brands_view') 
    else:

      form = BrandForm()  

    return render(request, 'brands_app/add_new_brand.html', {'form': form})  


def update_brand_view(request:HttpRequest , brand_id):
    brand = get_object_or_404(Brand, id=brand_id)  
    if request.method == 'POST':
        form = BrandForm(request.POST, request.FILES, instance=brand)  
        if form.is_valid():
            form.save()  # Save the updated brand
            messages.success(request, "Brand updated successfully!")
            return redirect('brand_detail_view', brand_id=brand.id) 
    else:
        form = BrandForm(instance=brand) 

    return render(request, 'brands_app/update_brand.html', {'form': form})


def brand_delete_view(request, brand_id):
    brand = get_object_or_404(Brand, id=brand_id)  
    if request.method == 'POST':
        brand.delete() 
        messages.success(request, "Brand deleted successfully!")
        return redirect('brands_app:all_brands_view')  
    return render(request, 'brands_app/delete_brand.html', {'brand': brand})  

 

CarsWebsite./ShowRoom/brands_app/templates/brands_app/add_new_brand.html
{% extends 'main_app/base.html' %}
{% load static %}
{% block title %}Create Brand{% endblock %}
{% block content %}
<div class="container mx-auto my-8">
    <h1 class="text-3xl font-bold mb-4">Create Brand</h1>
    <form method="post" enctype="multipart/form-data" class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
        {% csrf_token %}
        {{ form.as_p }}  <!-- Renders the form fields -->
        <div class="flex items-center justify-between">
            <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
                Create Brand
            </button>
        </div>
    </form>
    <a href="{% url 'brands_app:all_brands_view' %}" class="inline-block px-4 py-2 text-white bg-gray-500 rounded hover:bg-gray-600 mt-4">View All Brands</a>
</div>
{% endblock %}

CarsWebsite./ShowRoom/brands_app/templates/brands_app/all_brands.html
{% extends 'main_app/base.html' %}
{% load static %}
{% block title %}All Brands{% endblock %}
{% block content %}
<div class="container mx-auto my-8">
    <h1 class="text-3xl font-bold mb-4">All Brands</h1>
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
        {% for brand in brands %}
        <div class="bg-gray-800 rounded-lg shadow-md p-4">
            <a href="{%url 'brands_app:brand_detail_view' brand.id %}" class="font-semibold text-lg text-white">{{ brand.name }}</h3>
            <img src="{{ brand.logo.url }}" alt="{{ brand.name }}" class="w-full h-64 object-cover rounded-t-lg bg-white"> <!-- Fixed height -->
            <p class="text-white">Founded: {{ brand.founded_at }}</p>
        </div>
        {% empty %}
        <p class="text-center text-gray-500">No brands available.</p>
        {% endfor %}
    </div>
</div>
{% endblock %}

CarsWebsite./ShowRoom/brands_app/templates/brands_app/brand_detail.html
{% extends 'main_app/base.html' %}
{% load static %}
{% block title %}{{ brand.name }} Details{% endblock %}
{% block content %}
<div class="container mx-auto my-8">
    <h1 class="text-3xl font-bold mb-4">{{ brand.name }}</h1>
    <img src="{{ brand.logo.url }}" alt="{{ brand.name }}" class="w-50 object-cover mb-4 rounded-lg shadow-md items-center bg-white">
    <p class="text-lg"><strong>About:</strong> {{ brand.about }}</p>
    <p class="text-lg"><strong>Founded:</strong> {{ brand.founded_at }}</p>
    <p class="text-lg"><strong>Brand Type:</strong> {{ brand.get_brand_type_display }}</p>
    <p class="text-lg"><strong>Number of Cars:</strong> {{ brand.car_count }}</p>
    <div class="mt-4">
        <a href="{% url 'brands_app:update_brand_view' brand.id %}" class="inline-block px-4 py-2 text-white bg-yellow-500 rounded hover:bg-yellow-600">Edit Brand</a>
        <a href="{% url 'brands_app:brand_delete_view' brand.id %}" class=" inline-block  bg-red-600 text-white py-2 px-4 rounded">Delete Brand</a>
        <a href="{% url 'brands_app:all_brands_view' %}" class="inline-block px-4 py-2 text-white bg-gray-500 rounded hover:bg-gray-600 ml-2">Back to All Brands</a>

    </div>
</div>
{% endblock %}

CarsWebsite./ShowRoom/brands_app/templates/brands_app/delete_brand.html
{% extends 'main_app/base.html' %}
{% load static %}
{% block title %}Delete Brand{% endblock %}
{% block content %}
<div class="container mx-auto my-8">
    <h1 class="text-3xl font-bold mb-4">Delete Brand</h1>
    <p>Are you sure you want to delete the brand <strong>{{ brand.name }}</strong>?</p>
    <form method="post" class="mt-4">
        {% csrf_token %}
        <button type="submit" class="bg-red-600 hover:bg-red-700 text-white font-bold py-2 px-4 rounded">Delete</button>
        <a href="{% url 'brands_app:brand_detail_view' brand.id %}" class="ml-4 inline-block px-4 py-2 text-gray-700 bg-gray-300 rounded hover:bg-gray-400">Cancel</a>
    </form>
</div>
{% endblock %}

CarsWebsite./ShowRoom/brands_app/templates/brands_app/update_brand.html
{% extends 'main_app/base.html' %}
{% load static %}
{% block title %}{{ form.instance.id|yesno:"Edit Brand,Create Brand" }}{% endblock %}
{% block content %}
<div class="container mx-auto my-8">
    <h1 class="text-3xl font-bold mb-4">{{ form.instance.id|yesno:"Edit Brand,Create Brand" }}</h1>
    <form method="post" enctype="multipart/form-data" class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
        {% csrf_token %}
        {{ form.as_p }}  <!-- Renders the form fields -->
        <div class="flex items-center justify-between">
            <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
                {{ form.instance.id|yesno:"Update Brand,Create Brand" }}
            </button>
        </div>
    </form>
    <a href="{% url 'brands_app:all_brands_view' %}" class="inline-block px-4 py-2 text-white bg-gray-500 rounded hover:bg-gray-600 mt-4">Back to All Brands</a>
</div>
{% endblock %}