showroom/brands/urls.py
from django.urls import path
from . import views

app_name = 'brands'

urlpatterns = [
    path('all/', views.all_brands, name='all_brands'),
    path('details/<int:brand_id>/', views.brand_detail, name='brand_detail'),
    path('new/', views.new_brand, name='new_brand'),
    path('update/<int:brand_id>/', views.update_brand, name='update_brand'),
    path('delete/<int:brand_id>/', views.delete_brand, name='delete_brand'),
]

showroom/cars/urls.py
from django.urls import path
from . import views

app_name = 'cars'

urlpatterns = [
    path('all/', views.all_cars, name='all_cars'),
    path('details/<int:car_id>/', views.car_detail, name='car_detail'),
    path('new/', views.new_car, name='new_car'),
    path('update/<int:car_id>/', views.update_car, name='update_car'),
    path('delete/<int:car_id>/', views.delete_car, name='delete_car'),
    path('colors/new/', views.new_color, name='new_color'),
    path('colors/update/<int:color_id>/', views.update_color, name='update_color'),
    path('colors/delete/<int:color_id>/', views.delete_color, name='delete_color'),
    path('all_colors/', views.all_colors, name='all_colors'),

]

showroom/main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

showroom/showroom/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('cars/', include('cars.urls')),
    path('brands/', include('brands.urls')),
] +static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

showroom/brands/models.py
from django.db import models

class Brand(models.Model):
    name = models.CharField(max_length=100)
    logo = models.ImageField(upload_to='brands/logos/')
    about = models.TextField()
    founded_at = models.DateField()
    
    def __str__(self):
        return self.name

showroom/cars/models.py
from django.db import models
from brands.models import Brand

class Color(models.Model):
    name = models.CharField(max_length=50)
    color_code = models.CharField(max_length=7)  # Hex code (e.g., #FFFFFF)

    def __str__(self):
        return self.name


class Car(models.Model):
    name = models.CharField(max_length=100)
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE)
    colors = models.ManyToManyField(Color)
    photo = models.ImageField(upload_to='cars/photos/')
    specs = models.TextField()
    model = models.CharField(max_length=50)

    def __str__(self):
        return self.name

showroom/brands/forms.py
from django import forms
from .models import Brand

class BrandForm(forms.ModelForm):
    class Meta:
        model = Brand
        fields = ['name', 'logo', 'about', 'founded_at']

showroom/cars/forms.py
from django import forms
from .models import Car, Color

class CarForm(forms.ModelForm):
    class Meta:
        model = Car
        fields = ['name', 'brand', 'colors', 'photo', 'specs', 'model']


class ColorForm(forms.ModelForm):
    class Meta:
        model = Color
        fields = ['name', 'color_code']

showroom/brands/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Brand
from .forms import BrandForm
from django.contrib import messages

def all_brands(request):
    brands = Brand.objects.all()
    return render(request, 'brands/all_brands.html', {'brands': brands})


def brand_detail(request, brand_id):
    brand = get_object_or_404(Brand, id=brand_id)
    return render(request, 'brands/brand_detail.html', {'brand': brand})


def new_brand(request):
    if request.method == 'POST':
        form = BrandForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('brands:all_brands')
    else:
        form = BrandForm()
    return render(request, 'brands/new_brand.html', {'form': form})


def update_brand(request, brand_id):
    brand = get_object_or_404(Brand, id=brand_id)
    if request.method == 'POST':
        form = BrandForm(request.POST, request.FILES, instance=brand)
        if form.is_valid():
            form.save()
            return redirect('brands:brand_detail', brand_id=brand.id)
    else:
        form = BrandForm(instance=brand)

    return render(request, 'brands/update_brand.html', {'form': form, 'brand': brand})


def delete_brand(request, brand_id):
    brand = get_object_or_404(Brand, id=brand_id)
    if request.method == 'POST':
        brand.delete()
        messages.success(request, "Brand deleted successfully!")
        return redirect('brands:all_brands')
    return render(request, 'brands/delete_brand.html', {'brand': brand})

showroom/cars/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator
from cars.models import Car, Color
from .forms import CarForm, ColorForm
from brands.models import Brand
from django.contrib import messages


def all_cars(request):
    query = request.GET.get('search', '')
    cars = Car.objects.all()
    if query:
        cars = cars.filter(name__icontains=query)

    brands = Brand.objects.all()
    colors = Color.objects.all()
    paginator = Paginator(cars, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'cars/all_cars.html', {'page_obj': page_obj, 'brands': brands, 'colors': colors, 'query': query})


def car_detail(request, car_id):
    car = get_object_or_404(Car, id=car_id)
    return render(request, 'cars/car_detail.html', {'car': car})


def new_car(request):
    if request.method == 'POST':
        form = CarForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, "New car added successfully!")
            return redirect('cars:all_cars')
    else:
        form = CarForm()
    return render(request, 'cars/new_car.html', {'form': form})


def update_car(request, car_id):
    car = get_object_or_404(Car, id=car_id)
    if request.method == 'POST':
        form = CarForm(request.POST, request.FILES, instance=car)
        if form.is_valid():
            form.save()
            messages.success(request, "Car updated successfully!")
            return redirect('cars:all_cars')
    else:
        form = CarForm(instance=car)
    return render(request, 'cars/new_car.html', {'form': form})


def delete_car(request, car_id):
    car = get_object_or_404(Car, id=car_id)
    if request.method == 'POST':
        car.delete()
        messages.success(request, "Car deleted successfully!")
        return redirect('cars:all_cars')
    return render(request, 'cars/delete_car.html', {'car': car})


def new_color(request):
    if request.method == 'POST':
        form = ColorForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "New color added successfully!")
            return redirect('cars:all_cars')
    else:
        form = ColorForm()
    return render(request, 'cars/new_color.html', {'form': form})


def update_color(request, color_id):
    color = get_object_or_404(Color, id=color_id)
    if request.method == 'POST':
        form = ColorForm(request.POST, instance=color)
        if form.is_valid():
            form.save()
            messages.success(request, "Color updated successfully!")
            return redirect('cars:all_cars')
    else:
        form = ColorForm(instance=color)
    return render(request, 'cars/update_color.html', {'form': form, 'color': color})


def delete_color(request, color_id):
    color = get_object_or_404(Color, id=color_id)
    if request.method == 'POST':
        color.delete()
        messages.success(request, "Color deleted successfully!")
        return redirect('cars:all_colors')
    return render(request, 'cars/delete_color.html', {'color': color})


def all_colors(request):
    colors = Color.objects.all()
    return render(request, 'cars/all_colors.html', {'colors': colors})

showroom/main/views.py
from django.shortcuts import render
from cars.models import Car
from brands.models import Brand

def home(request):
    latest_cars = Car.objects.all().order_by('-id')[:4]
    latest_brands = Brand.objects.all().order_by('-id')[:4]
    return render(request, 'main/home.html', {'latest_cars': latest_cars, 'latest_brands': latest_brands})

showroom/cars/templates/cars/all_cars.html
{% extends 'main/base.html' %}

{% block title %}All Cars{% endblock %}

{% block content %}
<h2>All Cars</h2>
<a href="{% url 'cars:new_car' %}">Add New Car</a>
<ul>
    {% for car in page_obj %}
        <li>
            <a href="{% url 'cars:car_detail' car.id %}">{{ car.name }}</a>
            - {{ car.brand.name }}
            <a href="{% url 'cars:update_car' car.id %}">Update</a> |
            <a href="{% url 'cars:delete_car' car.id %}">Delete</a>
        </li>
    {% endfor %}
</ul>
<div class="pagination">
    {% for page_num in page_obj.paginator.page_range %}
        <a href="?page={{ page_num }}">{{ page_num }}</a>
    {% endfor %}
</div>
{% endblock %}

showroom/cars/templates/cars/all_colors.html
{% extends 'main/base.html' %}

{% block title %}All Colors{% endblock %}

{% block content %}
<h2>All Colors</h2>
<ul>
    {% for color in colors %}
    <li>{{ color.name }} 
        <a href="{% url 'cars:update_color' color.id %}">Edit</a> | 
        <a href="{% url 'cars:delete_color' color.id %}">Delete</a>
    </li>
    {% endfor %}
</ul>
<a href="{% url 'cars:new_color' %}">Add New Color</a>
{% endblock %}

showroom/cars/templates/cars/car_detail.html
{% extends 'main/base.html' %}

{% block title %}Car Details{% endblock %}

{% block content %}
<h2>{{ car.name }}</h2>
<img src="{{ car.photo.url }}" alt="{{ car.name }}">
<p>Brand: {{ car.brand.name }}</p>
<p>Model: {{ car.model }}</p>
<p>Specifications: {{ car.specs }}</p>
<p>Available Colors:</p>
<ul>
    {% for color in car.colors.all %}
        <li>{{ color.name }}</li>
    {% endfor %}
</ul>
<a href="{% url 'cars:update_car' car.id %}">Update</a> |
<a href="{% url 'cars:delete_car' car.id %}">Delete</a>
<a href="{% url 'cars:all_cars' %}">Back to All Cars</a>
{% endblock %}

showroom/cars/templates/cars/delete_car.html
{% extends 'main/base.html' %}

{% block title %}Delete Car{% endblock %}

{% block content %}
<h2>Delete Car</h2>
<p>Are you sure you want to delete "{{ car.name }}"?</p>
<form method="post">
    {% csrf_token %}
    <button type="submit">Yes, Delete</button>
</form>
<a href="{% url 'cars:car_detail' car.id %}">Cancel</a>
{% endblock %}

showroom/cars/templates/cars/delete_color.html
{% extends 'main/base.html' %}

{% block title %}Delete Color{% endblock %}

{% block content %}
<h2>Are you sure you want to delete {{ color.name }}?</h2>
<form method="post">
    {% csrf_token %}
    <button type="submit">Yes, Delete</button>
</form>
<a href="{% url 'cars:all_colors' %}">Cancel</a>
{% endblock %}

showroom/cars/templates/cars/new_car.html
{% extends 'main/base.html' %}

{% block title %}New Car{% endblock %}

{% block content %}
<h2>Add a New Car</h2>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Add Car</button>
</form>
{% endblock %}

showroom/cars/templates/cars/new_color.html
{% extends 'main/base.html' %}

{% block title %}Add/Update Color{% endblock %}

{% block content %}
<h2>{{ title }}</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
</form>
<a href="{% url 'cars:all_colors' %}">Back to All Colors</a>
{% endblock %}

showroom/cars/templates/cars/update_car.html
{% extends 'main/base.html' %}

{% block title %}Update Car{% endblock %}

{% block content %}
<h2>Update Car: {{ car.name }}</h2>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Update Car</button>
</form>
<a href="{% url 'cars:car_detail' car.id %}">Back to Car Details</a>
{% endblock %}

showroom/cars/templates/cars/update_color.html
{% extends 'main/base.html' %}

{% block title %}Add/Update Color{% endblock %}

{% block content %}
<h2>{{ title }}</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
</form>
<a href="{% url 'cars:all_colors' %}">Back to All Colors</a>
{% endblock %}